[pytest]
addopts = --verbose --cov-append --cov-report term --cov tinydb --timeout=30 --log-cli-level=DEBUG --capture=no
timeout_method = thread
log_cli = true
log_cli_level = DEBUG
log_file = pytest_debug.log
log_file_level = DEBUG
markers =
    timeout: marks test with timeout threshold
    xfail: marks test as expected to fail
    flaky: marks test as flaky (deselect with '-m "not flaky"')
